events:
  Binder:
    identifier: 1
    modifier: 0
    keycode: c
    state: true
    type: binder
    action: qert
  writer:
    identifier: 2
    modifier: 0
    keycode: x
    state: true
    type: writer
    action: One moment, map.


events:
    - id: Binder
    action: tyui
    keycode: A
    modifier: 10
    type: binder
