settings:
- !!com.pakotzy.poehelper.feature.Binder
  events:
  - !!com.pakotzy.poehelper.event.GenericEvent
    hotKey: Shift+C
    action: QERT;4
    enabled: true
  - !!com.pakotzy.poehelper.event.GenericEvent
    hotKey: Control+Up
    action: "+"
    enabled: true
  - !!com.pakotzy.poehelper.event.GenericEvent
    hotKey: Control+Down
    action: "-"
    enabled: true
- !!com.pakotzy.poehelper.feature.Writer
  events:
  - !!com.pakotzy.poehelper.event.GenericEvent
    action: /afk Wife's home. On duty!
    hotKey: Shift+S
    enabled: true
  - !!com.pakotzy.poehelper.event.GenericEvent
    action: /disconnect
    hotKey: Shift+Q
    enabled: true
- !!com.pakotzy.poehelper.feature.Crafter
  events:
  - !!com.pakotzy.poehelper.event.CrafterEvent
    hotKey: Control+L
    enabled: true
    links: 0
    sockets: 5
    r: 0
    g: 0
    b: 0
    mods:
      - Life
      - Energy shield