settings:
- !!com.pakotzy.poehelper.feature.Binder
  events:
  - !!com.pakotzy.poehelper.event.GenericEvent
    hotKey: C
    action: QERT;4
    enabled: true
- !!com.pakotzy.poehelper.feature.Writer
  events:
  - !!com.pakotzy.poehelper.event.GenericEvent
    action: /afk Wife's home. On duty!
    hotKey: SHIFT+S
    enabled: true
  - !!com.pakotzy.poehelper.event.GenericEvent
    action: /disconnect
    hotKey: SHIFT+Q
    enabled: true
- !!com.pakotzy.poehelper.feature.Crafter
  events:
  - !!com.pakotzy.poehelper.event.CrafterEvent
    hotKey: SHIFT+S
    enabled: false
    links: 6
    sockets: 6
    colors: R-B-G-R G-B